### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by chrismahony** [theislab/scanpy-tutorials#48]
Can you help me with a couple of general things?

My object looks like this:

AnnData object with n_obs × n_vars = 37814 × 1802
    obs: 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'log1p', 'hvg', 'pca', 'neighbors', 'umap', 'leiden', 'rank_genes_groups', 'leiden_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

As far as I am aware, 'leiden' contains the cluster ID of my cells. How can I copy this to another obs slot?

And, I have sample ID, from the loup output file. It is a CSV with cell barcode in one column and sample ID in the other. In R, using seurat, I would assinge this ID suing the following code, is there a similar way I can do this in python using scanpy?

aggr$sampleID=(samples_ID[match(rownames(aggr@meta.data),samples_ID$Barcode),2])

Finally, to perform DE in seurat, I would copy cluster ID to smaple ID using;
aggr$cluster_sampleID <- paste(Idents(aggr), aggr$sampleID, sep = "_")
What would be the best way to do this using Scanpy?

Many thanks,
Chris

**Comment by Zethson** [comment]
Hi,

please ask usage questions here: https://discourse.scverse.org/
