### ISSUE TITLE
pip can't find branch @spatial

### ISSUE THREAD

**Issue by franciscogrisanti** [theislab/scanpy-tutorials#9]
Hello! I'm triying to install the scanpy@spatial release but keep bumping into this error -> 

```python
pip install git+https://github.com/theislab/scanpy.git@spatial
```

```
Collecting git+https://github.com/theislab/scanpy.git@spatial
  Cloning https://github.com/theislab/scanpy.git (to revision spatial) to /tmp/pip-req-build-d8y5n7oc
  Running command git clone -q https://github.com/theislab/scanpy.git /tmp/pip-req-build-d8y5n7oc
  WARNING: Did not find branch or tag 'spatial', assuming revision or ref.
  Running command git checkout -q spatial
  error: pathspec 'spatial' did not match any file(s) known to git.
ERROR: Command errored out with exit status 1: git checkout -q spatial Check the logs for full command output.
...
```

Could you guys please help me out? Thanks in advance!

**Comment by franciscogrisanti** [comment]
Thanks @giovp 

I was able to use the install/use the new spatial methods. Great work btw!

**Comment by linanzhang** [comment]
> Yeah, the spatial branch was merged in master branch this week [theislab/scanpy#1024](https://github.com/theislab/scanpy/pull/1024)
> Just clone the repo and do `pip install --user .`
> Sorry, did not update the notebook yet.

Can you be specific about the command? What is the installation command explicitly?

**Comment by linanzhang** [comment]
Thank you. I saw this error
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`
and figured out the these commands are needed before installing spatial scanpy
`pip install xcrun`
`xcode-select --install`

**Comment by franciscogrisanti** [comment]
I think it's an issue of your git, apparently after you update to macOS to Catalina.

Try this fix 

https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/

Close, and re-open bash terminal and then run 

pip install git+https://github.com/theislab/scanpy.git
